import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{VersionedTransaction}from'@solana/web3.js';import'./style.css';
const SOL='So11111111111111111111111111111111111111112',USDC='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const short=s=>s?`${s.slice(0,4)}…${s.slice(-4)}`:'';
const ema=(a,n)=>{if(!a.length)return 0;const k=2/(n+1);return a.slice(1).reduce((v,x)=>x*k+v*(1-k),a[0])};
const rsi=a=>{if(a.length<15)return 50;let g=0,l=0;for(let i=a.length-14;i<a.length;i++){const d=a[i]-a[i-1];d>0?g+=d:l-=d}return l===0?100:100-(100/(1+(g/14)/(l/14)))};
function App(){const[wallet,setWallet]=useState(null),[sol,setSol]=useState(null),[usdc,setUsdc]=useState(null),[price,setPrice]=useState(null),[status,setStatus]=useState('Esperando conexión'),[amount,setAmount]=useState('0.01'),[side,setSide]=useState('SOL_USDC'),[quote,setQuote]=useState(null),[busy,setBusy]=useState(false),[sig,setSig]=useState(''),[bot,setBot]=useState(false),[signal,setSignal]=useState('WAIT'),[stats,setStats]=useState({e9:0,e21:0,r:50,m:0});const prices=useRef([]),timer=useRef(null);
async function market(){try{const d=await fetch('https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd').then(r=>r.json()),p=Number(d.solana.usd);if(!p)return;setPrice(p);prices.current=[...prices.current.slice(-59),p];const a=prices.current,e9=ema(a,9),e21=ema(a,21),rr=rsi(a),m=a.length>5?(p/a[a.length-6]-1)*100:0;setStats({e9,e21,r:rr,m});let s='WAIT';if(a.length>=21&&e9>e21&&rr>=50&&rr<70&&m>0)s='BUY';else if(a.length>=21&&e9<e21&&rr<=50&&rr>30&&m<0)s='SELL';setSignal(s)}catch{}}
useEffect(()=>{market();return()=>timer.current&&clearInterval(timer.current)},[]);
async function refresh(k=wallet){if(!k)return;try{const calls=[{jsonrpc:'2.0',id:1,method:'getBalance',params:[k]},{jsonrpc:'2.0',id:2,method:'getTokenAccountsByOwner',params:[k,{mint:USDC},{encoding:'jsonParsed'}]}];const[a,b]=await Promise.all(calls.map(body=>fetch('https://api.mainnet-beta.solana.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json())));setSol((Number(a?.result?.value||0)/1e9).toFixed(5));const vals=b?.result?.value||[];setUsdc(vals.reduce((n,x)=>n+Number(x.account.data.parsed.info.tokenAmount.uiAmount||0),0).toFixed(4))}catch{setStatus('No se pudieron actualizar los saldos')}}
async function connect(){try{const p=window.phantom?.solana;if(!p?.isPhantom)return setStatus('Abre esta app en Phantom');const r=await p.connect(),k=r.publicKey.toString();setWallet(k);setStatus('Phantom conectado');await refresh(k)}catch{setStatus('Conexión cancelada')}}
function toggleBot(){if(bot){clearInterval(timer.current);timer.current=null;setBot(false);setStatus('Bot detenido');return}prices.current=[];market();timer.current=setInterval(market,15000);setBot(true);setStatus('Bot activo: analizando mercado cada 15 s. No opera sin tu aprobación.')}
function useSignal(){if(signal==='BUY'){setSide('USDC_SOL');setAmount(usdc&&Number(usdc)>0?Math.min(Number(usdc),1).toFixed(2):'1')}else if(signal==='SELL'){setSide('SOL_USDC');setAmount(sol&&Number(sol)>0?Math.min(Math.max(Number(sol)-0.005,0),0.01).toFixed(4):'0.01')}else return setStatus('WAIT: no hay señal operable');setQuote(null);setStatus(`Señal ${signal} preparada. Cotiza y revisa antes de firmar.`)}
function flip(){setSide(x=>x==='SOL_USDC'?'USDC_SOL':'SOL_USDC');setQuote(null);setSig('');setAmount(side==='SOL_USDC'?'1':'0.01')}
async function getQuote(){const n=Number(amount);if(!n||n<=0)return setStatus('Ingresa una cantidad válida');setBusy(true);setQuote(null);setSig('');try{const raw=Math.floor(n*(side==='SOL_USDC'?1e9:1e6));const r=await fetch(`/api/quote?side=${side}&amount=${raw}`),d=await r.json();if(!r.ok)throw new Error(d.error||'Error de cotización');setQuote(d);const out=Number(d.outAmount)/(side==='SOL_USDC'?1e6:1e9);setStatus(`Cotización lista: ≈ ${out.toFixed(side==='SOL_USDC'?4:6)} ${side==='SOL_USDC'?'USDC':'SOL'}`)}catch(e){setStatus(e.message)}finally{setBusy(false)}}
async function execute(){if(!wallet||!quote)return setStatus('Conecta Phantom y solicita una cotización');setBusy(true);try{const r=await fetch('/api/swap',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userPublicKey:wallet,quoteResponse:quote})}),d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo preparar la transacción');const bytes=Uint8Array.from(atob(d.swapTransaction),c=>c.charCodeAt(0)),tx=VersionedTransaction.deserialize(bytes);setStatus('Revisa la transacción en Phantom antes de aprobar');const result=await window.phantom.solana.signAndSendTransaction(tx);setSig(result.signature);setStatus(`Enviada: ${short(result.signature)}`);setQuote(null);setTimeout(()=>refresh(wallet),5000)}catch(e){setStatus(e?.message||'Operación cancelada')}finally{setBusy(false)}}
const out=quote?Number(quote.outAmount)/(side==='SOL_USDC'?1e6:1e9):0;
return <main><header><div><b>◎ SOLANA TRADING LAB</b><span>Bot de señales + ejecución con confirmación</span></div><button onClick={connect}>{wallet?short(wallet):'Conectar Phantom'}</button></header><section className="hero"><div><small>SOL / USD</small><h1>{price?`$${price.toLocaleString()}`:'Cargando…'}</h1><p>Mercado · Mainnet</p></div><div className="mode"><b>{bot?'BOT ACTIVO':'BOT DETENIDO'}</b><span>Cada swap requiere aprobación</span></div></section><section className="grid"><article><label>SOL real</label><h2>{sol??'—'}</h2><p>Saldo Phantom</p></article><article><label>USDC real</label><h2>{usdc??'—'}</h2><p>Saldo Phantom</p></article><article><label>Señal</label><h2>{signal}</h2><p>EMA 9/21 · RSI · momentum</p></article><article><label>Protección</label><h2>1% / 2%</h2><p>Slippage / impacto máximo</p></article></section><section className="panel"><div className="swaphead"><h3>Bot de señales</h3><button onClick={toggleBot}>{bot?'■ DETENER BOT':'▶ INICIAR BOT'}</button></div><p>EMA9 {stats.e9?stats.e9.toFixed(2):'—'} · EMA21 {stats.e21?stats.e21.toFixed(2):'—'} · RSI {stats.r.toFixed(1)} · Momentum {stats.m.toFixed(3)}%</p><button className="secondary" disabled={!bot||signal==='WAIT'} onClick={useSignal}>Preparar operación sugerida ({signal})</button><div className="notice">El bot analiza y genera señales; no firma ni mueve fondos automáticamente. BUY/SELL son señales mecánicas, no garantía de beneficio. Tú revisas la cotización y autorizas cada operación en Phantom.</div></section><section className="panel"><div className="swaphead"><h3>Swap real · {side==='SOL_USDC'?'SOL → USDC':'USDC → SOL'}</h3><button className="secondary" onClick={flip} disabled={busy}>⇄ Invertir</button></div><div className="metrics"><span>Cantidad {side==='SOL_USDC'?'SOL':'USDC'} <input value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null)}} inputMode="decimal"/></span><button disabled={busy} onClick={getQuote}>{busy?'Procesando…':'Cotizar Jupiter'}</button><button disabled={busy||!wallet||!quote} onClick={execute}>Revisar y aprobar en Phantom</button><button className="secondary" disabled={!wallet||busy} onClick={()=>refresh()}>Actualizar saldos</button></div>{quote&&<p>Recibirías aprox. <b>{out.toFixed(side==='SOL_USDC'?4:6)} {side==='SOL_USDC'?'USDC':'SOL'}</b> · impacto {(Number(quote.priceImpactPct)*100).toFixed(3)}%</p>}{sig&&<p className="success">✓ Transacción enviada · <a href={`https://solscan.io/tx/${sig}`} target="_blank" rel="noreferrer">Ver en Solscan ↗</a></p>}</section><footer>{status}</footer></main>}
createRoot(document.getElementById('app')).render(<App/>);