import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{VersionedTransaction}from'@solana/web3.js';import'./style.css';
const short=s=>s?`${s.slice(0,4)}…${s.slice(-4)}`:'';
function App(){const[wallet,setWallet]=useState(null),[sol,setSol]=useState(null),[price,setPrice]=useState(null),[paper]=useState(100),[status,setStatus]=useState('Esperando conexión'),[amount,setAmount]=useState('0.01'),[quote,setQuote]=useState(null),[busy,setBusy]=useState(false);
useEffect(()=>{fetch('https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd').then(r=>r.json()).then(d=>setPrice(d.solana.usd)).catch(()=>setStatus('No se pudo actualizar precio'));},[]);
async function connect(){try{const p=window.phantom?.solana;if(!p?.isPhantom){setStatus('Abre esta app en el navegador de Phantom o instala Phantom');return}const r=await p.connect();const k=r.publicKey.toString();setWallet(k);setStatus('Phantom conectado');try{const rpc=await fetch('https://api.mainnet-beta.solana.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getBalance',params:[k]})}).then(x=>x.json());setSol((rpc.result.value/1e9).toFixed(5))}catch{setSol('—')}}catch{setStatus('Conexión cancelada')}}
async function getQuote(){const n=Number(amount);if(!n||n<=0)return setStatus('Ingresa una cantidad válida');setBusy(true);setQuote(null);try{const lamports=Math.floor(n*1e9);const r=await fetch(`/api/quote?side=SOL_USDC&amount=${lamports}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Error de cotización');setQuote(d);setStatus(`Cotización lista: ≈ ${(Number(d.outAmount)/1e6).toFixed(4)} USDC`)}catch(e){setStatus(e.message)}finally{setBusy(false)}}
async function execute(){if(!wallet||!quote)return setStatus('Conecta Phantom y solicita una cotización');setBusy(true);try{const r=await fetch('/api/swap',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userPublicKey:wallet,quoteResponse:quote})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo preparar la transacción');const bytes=Uint8Array.from(atob(d.swapTransaction),c=>c.charCodeAt(0));const tx=VersionedTransaction.deserialize(bytes);setStatus('Revisa la transacción en Phantom antes de aprobar');const result=await window.phantom.solana.signAndSendTransaction(tx);setStatus(`Enviada: ${short(result.signature)}`);setQuote(null)}catch(e){setStatus(e?.message||'Operación cancelada')}finally{setBusy(false)}}
return <main><header><div><b>◎ SOLANA TRADING LAB</b><span>Terminal educativa</span></div><button onClick={connect}>{wallet?short(wallet):'Conectar Phantom'}</button></header><section className="hero"><div><small>SOL / USD</small><h1>{price?`$${price.toLocaleString()}`:'Cargando…'}</h1><p>Mercado · Mainnet</p></div><div className="mode"><b>PAPER + LIVE MANUAL</b><span>LIVE requiere aprobación en Phantom</span></div></section><section className="grid"><article><label>Wallet</label><h2>{wallet?short(wallet):'No conectada'}</h2><p>{sol?`${sol} SOL`:'Solo lectura hasta conectar'}</p></article><article><label>Balance paper</label><h2>${paper.toFixed(2)}</h2><p>Capital simulado</p></article><article><label>Señal</label><h2>WAIT</h2><p>EMA 9/21 · RSI · Momentum · Volatilidad</p></article><article><label>Riesgo</label><h2>1.0%</h2><p>Sin martingala · límite de pérdida</p></article></section><section className="panel"><h3>Swap real · SOL → USDC</h3><div className="metrics"><span>Cantidad SOL <input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></span><button disabled={busy} onClick={getQuote}>Cotizar Jupiter</button><button disabled={busy||!wallet||!quote} onClick={execute}>Revisar y aprobar en Phantom</button></div>{quote&&<p>Recibirías aprox. <b>{(Number(quote.outAmount)/1e6).toFixed(4)} USDC</b> · impacto {(Number(quote.priceImpactPct)*100).toFixed(3)}%</p>}<div className="notice">La app nunca almacena tu clave privada. El API key de Jupiter queda del lado del servidor. Toda operación real se muestra en Phantom y requiere tu aprobación explícita.</div></section><footer>{status}</footer></main>}
createRoot(document.getElementById('app')).render(<App/>);
